apiVersion: v1
kind: Pod
metadata:
  name: bazel-builder
spec:
  restartPolicy: Never
  containers:
  - name: bazel-builder
    image: debian:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "12Gi"
        cpu: "2"
      limits:
        memory: "12Gi"
        cpu: "2"
